from __future__ import annotations

CVM_FUND_DAILY_OBSERVATION_COLUMNS = [
    "ref_date",
    "available_date",
    "availability_policy",
    "fund_id",
    "fund_type",
    "portfolio_value",
    "nav",
    "quota_value",
    "subscriptions",
    "redemptions",
    "shareholder_count",
    "raw_vl_total",
    "raw_vl_patrim_liq",
    "raw_vl_quota",
    "raw_captc_dia",
    "raw_resg_dia",
    "raw_nr_cotst",
    "has_portfolio_value",
    "has_nav",
    "has_quota_value",
    "has_subscriptions",
    "has_redemptions",
    "has_shareholder_count",
    "source_version",
]

CVM_FUND_GROUP_OBSERVATION_COLUMNS = [
    "ref_date",
    "available_date",
    "group_type",
    "group_value",
    "feature_id",
    "portfolio_value",
    "nav",
    "subscriptions",
    "redemptions",
    "shareholder_count",
    "fund_count",
    "portfolio_value_count",
    "nav_count",
    "subscriptions_count",
    "redemptions_count",
    "shareholder_count_count",
    "source_version",
]

CVM_FUND_FLOWS_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "observation_ref_date",
    "observation_available_date",
    "group_type",
    "group_value",
    "feature_id",
    "subscriptions",
    "redemptions",
    "subscriptions_count",
    "redemptions_count",
    "fund_count",
    "source_version",
]

CVM_FUND_STATE_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "group_type",
    "group_value",
    "feature_id",
    "observation_ref_date",
    "observation_available_date",
    "portfolio_value",
    "nav",
    "shareholder_count",
    "fund_count",
    "portfolio_value_count",
    "nav_count",
    "shareholder_count_count",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "source_version",
]

CVM_FUND_REGISTRY_CURRENT_REFERENCE_COLUMNS = [
    "fund_id",
    "fund_type",
    "fund_name",
    "cvm_code",
    "registration_date",
    "constitution_date",
    "cancellation_date",
    "status",
    "status_start_date",
    "activity_start_date",
    "class_name",
    "class_start_date",
    "benchmark_or_return_target",
    "condominium_type",
    "is_fund_of_funds",
    "is_exclusive",
    "is_long_term_tax",
    "public_target",
    "admin_id",
    "admin_name",
    "manager_id",
    "manager_name",
    "custodian_id",
    "custodian_name",
    "auditor_id",
    "auditor_name",
    "controller_id",
    "controller_name",
    "snapshot_date",
    "source_version",
]

CVM_DAILY_LONG_COLUMNS = [
    "ref_date",
    "available_date",
    "source_family",
    "feature_id",
    "value_name",
    "value",
    "unit",
    "observation_ref_date",
    "observation_available_date",
    "is_available",
    "staleness_days",
    "source_version",
]

PANEL_PRIMARY_KEYS = {
    "fund_daily_observation": ["ref_date", "fund_id"],
    "fund_group_observation": ["ref_date", "group_type", "group_value"],
    "fund_flows_daily": ["ref_date", "group_type", "group_value", "observation_ref_date"],
    "fund_state_asof_daily": ["ref_date", "feature_id"],
    "fund_registry_current_reference": ["fund_id"],
    "daily_long": [
        "ref_date",
        "source_family",
        "feature_id",
        "value_name",
        "observation_ref_date",
    ],
}
