from __future__ import annotations

TESOURO_DIRETO_PRICES_RATES_OBSERVATION_COLUMNS = [
    "ref_date",
    "available_date",
    "security_name",
    "security_type",
    "maturity_date",
    "feature_id",
    "buy_rate",
    "sell_rate",
    "buy_price",
    "sell_price",
    "unit",
    "has_rate",
    "has_price",
    "source_version",
]

TESOURO_DIRETO_PRICES_RATES_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "feature_id",
    "security_name",
    "security_type",
    "maturity_date",
    "observation_ref_date",
    "observation_available_date",
    "buy_rate",
    "sell_rate",
    "buy_price",
    "sell_price",
    "unit",
    "has_rate",
    "has_price",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "source_version",
]

TESOURO_DIRETO_FLOWS_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "observation_ref_date",
    "observation_available_date",
    "flow_type",
    "redemption_type",
    "security_name",
    "security_type",
    "maturity_date",
    "feature_id",
    "quantity",
    "value",
    "investor_count",
    "unit",
    "source_dataset",
    "source_version",
]

TESOURO_DIRETO_STOCK_OBSERVATION_COLUMNS = [
    "ref_date",
    "available_date",
    "security_name",
    "security_type",
    "maturity_date",
    "feature_id",
    "quantity",
    "stock_value",
    "investor_count",
    "unit",
    "source_version",
]

TESOURO_DIRETO_STOCK_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "feature_id",
    "security_name",
    "security_type",
    "maturity_date",
    "observation_ref_date",
    "observation_available_date",
    "quantity",
    "stock_value",
    "investor_count",
    "unit",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "source_version",
]

TESOURO_DPF_STOCK_OBSERVATION_COLUMNS = [
    "ref_date",
    "available_date",
    "debt_category",
    "instrument_type",
    "indexer",
    "holder_or_maturity_bucket",
    "feature_id",
    "stock_value",
    "unit",
    "source_version",
]

TESOURO_DPF_STOCK_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "feature_id",
    "debt_category",
    "instrument_type",
    "indexer",
    "holder_or_maturity_bucket",
    "observation_ref_date",
    "observation_available_date",
    "stock_value",
    "unit",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "source_version",
]

TESOURO_DAILY_LONG_COLUMNS = [
    "ref_date",
    "available_date",
    "source_family",
    "feature_id",
    "value_name",
    "value",
    "unit",
    "observation_ref_date",
    "observation_available_date",
    "is_available",
    "staleness_days",
    "source_version",
]

PANEL_PRIMARY_KEYS = {
    "direto_prices_rates_observation": ["ref_date", "security_name", "maturity_date"],
    "direto_prices_rates_asof_daily": ["ref_date", "feature_id"],
    "direto_flows_daily": [
        "ref_date",
        "flow_type",
        "redemption_type",
        "security_name",
        "maturity_date",
    ],
    "direto_stock_observation": ["ref_date", "security_name", "maturity_date"],
    "direto_stock_asof_daily": ["ref_date", "feature_id"],
    "dpf_stock_observation": [
        "ref_date",
        "debt_category",
        "indexer",
        "holder_or_maturity_bucket",
    ],
    "dpf_stock_asof_daily": ["ref_date", "feature_id"],
    "daily_long": ["ref_date", "source_family", "feature_id", "value_name"],
}
