from __future__ import annotations

BCB_SGS_OBSERVATION_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "series_id",
    "series_slug",
    "series_name",
    "category",
    "frequency",
    "value",
    "unit",
    "availability_policy",
    "availability_basis",
    "revision_policy",
    "model_usable",
    "source_reference_url",
    "notes",
    "non_model_usable_reason",
    "alternate_source_family",
    "reference_feature_family",
    "source_version",
]

BCB_SGS_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "series_id",
    "series_slug",
    "series_name",
    "category",
    "frequency",
    "observation_ref_date",
    "observation_available_date",
    "value",
    "unit",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "availability_policy",
    "availability_basis",
    "revision_policy",
    "model_usable",
    "source_reference_url",
    "notes",
    "non_model_usable_reason",
    "alternate_source_family",
    "reference_feature_family",
    "source_version",
]

BCB_SGS_FEATURE_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "source_family",
    "feature_id",
    "value_name",
    "value",
    "unit",
    "observation_ref_date",
    "observation_available_date",
    "availability_policy",
    "availability_basis",
    "revision_policy",
    "model_usable",
    "is_available",
    "staleness_days",
    "source_version",
]

BCB_PTAX_FEATURE_DAILY_COLUMNS = list(BCB_SGS_FEATURE_DAILY_COLUMNS)

BCB_FOCUS_FEATURE_DAILY_COLUMNS = list(BCB_SGS_FEATURE_DAILY_COLUMNS)

BCB_PTAX_SELECTED_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "currency_code",
    "currency_name",
    "selected_bulletin_type",
    "quote_datetime",
    "bid_rate",
    "ask_rate",
    "bid_parity",
    "ask_parity",
    "has_quote",
    "source_version",
]

BCB_FOCUS_EXPECTATION_OBSERVATION_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "expectation_key",
    "endpoint",
    "indicator",
    "indicator_detail",
    "reference_period",
    "reference_year",
    "reference_month",
    "meeting",
    "horizon_label",
    "is_top5",
    "calculation_type",
    "statistic_scope",
    "mean",
    "median",
    "std_dev",
    "min_value",
    "max_value",
    "respondents",
    "base_calculation",
    "availability_note",
    "source_dataset",
    "source_version",
]

BCB_FOCUS_EXPECTATION_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "expectation_key",
    "observation_ref_date",
    "observation_available_date",
    "endpoint",
    "indicator",
    "indicator_detail",
    "reference_period",
    "reference_year",
    "reference_month",
    "meeting",
    "horizon_label",
    "is_top5",
    "calculation_type",
    "statistic_scope",
    "mean",
    "median",
    "std_dev",
    "min_value",
    "max_value",
    "respondents",
    "base_calculation",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "availability_note",
    "source_dataset",
    "source_version",
]

BCB_FOCUS_REFERENCE_DATES_COLUMNS = [
    "indicator",
    "period",
    "reference_date_type",
    "reference_date",
    "available_date",
    "raw_reference_date",
    "source_version",
]

BCB_DAILY_LONG_COLUMNS = [
    "ref_date",
    "available_date",
    "source_family",
    "feature_id",
    "value_name",
    "value",
    "unit",
    "observation_ref_date",
    "observation_available_date",
    "availability_policy",
    "availability_basis",
    "revision_policy",
    "model_usable",
    "is_available",
    "staleness_days",
    "source_version",
]

PANEL_PRIMARY_KEYS = {
    "sgs_observation_daily": ["series_id", "ref_date"],
    "sgs_asof_daily": ["ref_date", "series_id"],
    "sgs_feature_daily": ["ref_date", "feature_id", "value_name"],
    "ptax_feature_daily": ["ref_date", "feature_id", "value_name"],
    "ptax_selected_daily": ["ref_date", "currency_code"],
    "focus_expectation_observation_daily": ["expectation_key", "ref_date"],
    "focus_expectation_asof_daily": ["ref_date", "expectation_key"],
    "focus_feature_daily": ["ref_date", "feature_id", "value_name"],
    "focus_reference_dates": [
        "indicator",
        "period",
        "reference_date_type",
        "reference_date",
    ],
    "daily_long": ["ref_date", "source_family", "feature_id", "value_name"],
}
