from __future__ import annotations

NOVO_CAGED_MOVEMENT_RECORD_OBSERVATION_COLUMNS = [
    "movement_record_id",
    "ref_date",
    "available_date",
    "availability_policy",
    "competence",
    "year",
    "month",
    "record_kind",
    "region",
    "state",
    "municipality_code",
    "cnae_section",
    "cnae_subclass",
    "occupation_code",
    "movement_type_code",
    "movement_sign",
    "employment_category",
    "education_degree",
    "age",
    "sex",
    "race_color",
    "disability_type",
    "employer_type",
    "establishment_type",
    "establishment_size_jan",
    "contract_hours",
    "wage",
    "wage_unit",
    "is_apprentice",
    "is_intermittent",
    "is_part_time",
    "source_system",
    "has_wage",
    "has_contract_hours",
    "source_version",
]

NOVO_CAGED_RELEASE_CALENDAR_REFERENCE_COLUMNS = [
    "ref_date",
    "release_date",
    "available_date",
    "availability_policy",
    "release_year",
    "competence_label",
    "source_version",
]

NOVO_CAGED_MOVEMENT_GROUP_OBSERVATION_COLUMNS = [
    "ref_date",
    "available_date",
    "silver_available_date",
    "calendar_available_date",
    "availability_source",
    "availability_policy",
    "group_type",
    "group_value",
    "movement_sign",
    "feature_id",
    "movement_count",
    "wage_mean",
    "contract_hours_mean",
    "wage_count",
    "contract_hours_count",
    "source_version",
]

NOVO_CAGED_STATE_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "source_family",
    "feature_id",
    "observation_ref_date",
    "observation_available_date",
    "value_name",
    "value",
    "unit",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "source_version",
]

NOVO_CAGED_DAILY_LONG_COLUMNS = [
    "ref_date",
    "available_date",
    "source_family",
    "feature_id",
    "value_name",
    "value",
    "unit",
    "observation_ref_date",
    "observation_available_date",
    "is_available",
    "staleness_days",
    "source_version",
]

PANEL_PRIMARY_KEYS = {
    "movement_record_observation": ["movement_record_id"],
    "release_calendar_reference": ["ref_date"],
    "movement_group_observation": [
        "ref_date",
        "group_type",
        "group_value",
        "movement_sign",
    ],
    "state_asof_daily": ["ref_date", "source_family", "feature_id", "value_name"],
    "daily_long": ["ref_date", "source_family", "feature_id", "value_name"],
}
