from __future__ import annotations

IBGE_SIDRA_OBSERVATION_COLUMNS = [
    "dataset_slug",
    "aggregate_id",
    "variable_id",
    "variable_name",
    "unit",
    "frequency",
    "period_code",
    "period_label",
    "ref_period_start",
    "ref_period_end",
    "ref_date",
    "release_date",
    "available_datetime_local",
    "available_datetime_utc",
    "available_date",
    "availability_policy",
    "availability_basis",
    "revision_policy",
    "vintage_id",
    "first_seen_timestamp_utc",
    "source_publication_datetime_utc",
    "availability_note",
    "model_usable",
    "geography_level",
    "geography_id",
    "geography_name",
    "classification_key",
    "classifications_json",
    "value",
    "raw_value",
    "value_status",
    "has_value",
    "source_version",
]

IBGE_SIDRA_ASOF_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "feature_id",
    "dataset_slug",
    "aggregate_id",
    "variable_id",
    "variable_name",
    "unit",
    "frequency",
    "observation_ref_date",
    "observation_available_date",
    "ref_period_start",
    "ref_period_end",
    "period_code",
    "period_label",
    "release_date",
    "available_datetime_local",
    "available_datetime_utc",
    "availability_policy",
    "availability_basis",
    "revision_policy",
    "vintage_id",
    "first_seen_timestamp_utc",
    "source_publication_datetime_utc",
    "geography_level",
    "geography_id",
    "geography_name",
    "classification_key",
    "classifications_json",
    "value",
    "raw_value",
    "value_status",
    "has_value",
    "is_available",
    "is_observed_on_ref_date",
    "staleness_days",
    "source_version",
]

IBGE_RELEASE_CALENDAR_REFERENCE_COLUMNS = [
    "event_id",
    "product_id",
    "product_name",
    "survey_code",
    "survey_name",
    "release_title",
    "release_date",
    "release_time_local",
    "available_datetime_local",
    "available_datetime_utc",
    "available_date",
    "availability_policy",
    "reference_period",
    "reference_period_start",
    "reference_period_end",
    "source_version",
]

IBGE_PRODUCTS_REFERENCE_COLUMNS = [
    "product_id",
    "product_name",
    "product_type",
    "parent_product_id",
    "alias",
    "acronym",
    "category_id",
    "category_name",
    "parent_category_id",
    "parent_category_name",
    "path",
    "source_version",
]

IBGE_NEWS_RELEASE_METADATA_COLUMNS = [
    "news_id",
    "product_id",
    "product_name",
    "title",
    "type",
    "published_datetime_local",
    "published_datetime_utc",
    "published_date",
    "available_date",
    "url",
    "source_version",
]

IBGE_DAILY_LONG_COLUMNS = [
    "ref_date",
    "available_date",
    "source_family",
    "feature_id",
    "value_name",
    "value",
    "unit",
    "observation_ref_date",
    "observation_available_date",
    "availability_policy",
    "availability_basis",
    "revision_policy",
    "vintage_id",
    "first_seen_timestamp_utc",
    "source_publication_datetime_utc",
    "is_available",
    "has_value",
    "staleness_days",
    "value_status",
    "source_version",
]

PANEL_PRIMARY_KEYS = {
    "sidra_observation": [
        "dataset_slug",
        "aggregate_id",
        "variable_id",
        "period_code",
        "geography_id",
        "classification_key",
    ],
    "sidra_asof_daily": ["ref_date", "feature_id"],
    "release_calendar_reference": ["event_id"],
    "products_reference": ["product_id"],
    "news_release_metadata": ["news_id"],
    "daily_long": ["ref_date", "source_family", "feature_id", "value_name"],
}
