from __future__ import annotations

FUTURES_CONTRACT_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "root",
    "commodity",
    "maturity_code",
    "contract_id",
    "symbol",
    "asset_class",
    "maturity_date",
    "days_to_maturity_calendar",
    "business_days_to_maturity",
    "calendar_source",
    "contract_rank_by_maturity",
    "settlement",
    "previous_settlement",
    "price_change",
    "settlement_value",
    "volume",
    "financial_volume",
    "number_of_trades",
    "open_interest",
    "currency",
    "unit",
    "quote_convention",
    "is_tradeable",
    "has_settlement",
    "has_volume",
    "has_open_interest",
    "source_datasets",
    "source_version",
]

CONTINUOUS_FUTURES_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "continuous_id",
    "root",
    "rank",
    "selected_contract_id",
    "selected_maturity_code",
    "selected_maturity_date",
    "days_to_maturity_calendar",
    "business_days_to_maturity",
    "roll_policy",
    "is_roll_date",
    "previous_contract_id",
    "settlement",
    "quote_diff_1d",
    "quote_pct_change_1d",
    "same_contract_quote_diff_1d",
    "same_contract_quote_pct_change_1d",
    "volume",
    "open_interest",
    "is_tradeable",
    "source_version",
]

DI_CURVE_CONTRACT_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "contract_id",
    "maturity_code",
    "maturity_date",
    "days_to_maturity_calendar",
    "business_days_to_maturity",
    "calendar_source",
    "contract_rank_by_maturity",
    "raw_settlement_pu",
    "discount_factor",
    "log_discount_factor",
    "implied_annual_rate",
    "implied_annual_rate_bp",
    "curve_value",
    "curve_value_kind",
    "curve_value_diff_1d",
    "curve_value_pct_change_1d",
    "implied_annual_rate_bp_change_1d",
    "log_discount_factor_change_1d",
    "volume",
    "open_interest",
    "is_observed",
    "source_version",
]

DI_CURVE_GRID_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "curve_id",
    "tenor_days",
    "tenor_business_days",
    "curve_value",
    "curve_value_kind",
    "discount_factor",
    "log_discount_factor",
    "implied_annual_rate",
    "implied_annual_rate_bp",
    "interpolation_method",
    "left_contract_id",
    "right_contract_id",
    "left_days_to_maturity",
    "right_days_to_maturity",
    "is_interpolated",
    "is_extrapolated",
    "has_curve_value",
    "source_version",
]

LISTED_MARKET_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "symbol",
    "isin",
    "market_type",
    "asset_class",
    "name",
    "open",
    "high",
    "low",
    "close",
    "average",
    "best_bid",
    "best_ask",
    "volume",
    "financial_volume",
    "number_of_trades",
    "source_dataset",
    "source_version",
]

INDEX_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "index_id",
    "close",
    "open",
    "high",
    "low",
    "volume",
    "financial_volume",
    "number_of_trades",
    "currency",
    "unit",
    "source_version",
]

INDEX_COMPOSITION_DAILY_COLUMNS = [
    "ref_date",
    "available_date",
    "index_id",
    "symbol",
    "isin",
    "security_id",
    "name",
    "weight",
    "theoretical_quantity",
    "source_dataset",
    "source_version",
]

TARGETS_DAILY_COLUMNS = [
    "ref_date",
    "label_available_date",
    "target_id",
    "asset_family",
    "horizon",
    "target_type",
    "target_start_date",
    "target_end_date",
    "target_value",
    "source_version",
]

PANEL_PRIMARY_KEYS = {
    "futures_contract_daily": ["ref_date", "contract_id"],
    "continuous_futures_daily": ["ref_date", "continuous_id"],
    "di_curve_contract_daily": ["ref_date", "contract_id"],
    "di_curve_grid_daily": ["ref_date", "curve_id", "tenor_days"],
    "listed_market_daily": ["ref_date", "symbol", "market_type"],
    "index_daily": ["ref_date", "index_id"],
    "index_composition_daily": ["ref_date", "index_id", "symbol", "source_dataset"],
    "targets_daily": ["ref_date", "target_id", "horizon", "target_type"],
}
