"""Recover the completed account/source work and bounded data intermediates."""

import hashlib
import json
from pathlib import Path
import subprocess
from time import perf_counter
import zipfile

from brazil_rv.v2.artifacts import write_json_atomic
from brazil_rv.v2.data_repair import binding, bound_json

PROJECT = Path(__file__).resolve().parents[1]


def main():
    tick = perf_counter()
    pointer = PROJECT / "docs/v2_economic_data_scaling_run.json"
    run = json.loads(pointer.read_text(encoding="utf8"))
    base = Path(run["stage_c_root"])
    commit = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=PROJECT, text=True
    ).strip()
    archive = Path(run["root"]) / f"matched_economics_{commit[:7]}.zip"
    assert not archive.exists()
    dependencies = {
        k: run[k]
        for k in (
            "integrated_account_recovery",
            "composed_store_recovery",
            "surviving_rename_market_recovery",
            "surviving_rename_dependency_recovery",
            "surviving_rename_recovery",
            "lending_feature_recovery",
        )
    }
    for record in dependencies.values():
        bound_json(record)
    members, unique, aliases = {}, {}, {}
    # Frozen enumeration excludes generated bytecode and retains every attempt.
    evidence = sorted(
        p for p in base.rglob("*") if p.is_file() and "__pycache__" not in p.parts
    )
    assert all(
        not p.is_symlink() and p.resolve().is_relative_to(base.resolve())
        for p in evidence
    )
    assert not any("policy_data.pkl" == p.name for p in evidence)
    project_paths = subprocess.check_output(
        ["git", "ls-files", "research", "ops"], cwd=PROJECT, text=True
    ).splitlines()
    project_paths += [
        "PROJECT_CONTEXT.md",
        "docs/v2_MATCHED_ECONOMIC_REPLAYS.md",
        "docs/v2_economic_data_scaling_progress.md",
        "docs/v2_economic_data_scaling_run.json",
        "docs/v2_CORPORATE_ACCOUNT.md",
    ]
    with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:

        def add(name, data):
            assert name not in members
            digest = hashlib.sha256(data).hexdigest()
            members[name] = dict(sha256=digest, bytes=len(data))
            if digest in unique:
                aliases[name] = unique[digest]
            else:
                unique[digest] = name
                z.writestr(name, data)

        for name in sorted(set(project_paths)):
            add("project/" + name, (PROJECT / name).read_bytes())
        add(
            "implementation.patch",
            subprocess.check_output(["git", "diff", "18ce035", "HEAD"], cwd=PROJECT),
        )
        for p in evidence:
            add("evidence/" + p.relative_to(base).as_posix(), p.read_bytes())
        add("dependencies.json", json.dumps(dependencies, indent=2).encode())
        z.writestr("aliases.json", json.dumps(aliases, indent=2))
        z.writestr("members.json", json.dumps(members, indent=2))
    archived_seconds = perf_counter() - tick
    print(
        json.dumps(dict(archived_bytes=archive.stat().st_size, members=len(members))),
        flush=True,
    )
    # One scratch file at a time avoids duplicating the full evidence tree.
    scratch = base / f"recovery_scratch_{commit[:7]}"
    scratch.mkdir(exist_ok=False)
    restored = scratch / "member.bin"
    with zipfile.ZipFile(archive) as z:
        for name, record in members.items():
            data = z.read(aliases.get(name, name))
            assert hashlib.sha256(data).hexdigest() == record["sha256"]
            assert len(data) == record["bytes"]
            restored.write_bytes(data)
            assert hashlib.sha256(restored.read_bytes()).hexdigest() == record["sha256"]
            restored.unlink()
    scratch.rmdir()
    report = dict(
        status="verified",
        implementation_commit=commit,
        archive={**binding(archive), "bytes": archive.stat().st_size},
        logical_members=len(members),
        unique_members=len(unique),
        aliases=len(aliases),
        restored_bytes=sum(v["bytes"] for v in members.values()),
        recovery_method="Restore/hash-check every logical member one at a time, then remove only its scratch copy; all original evidence remains.",
        evidence={
            k: v
            for k, v in run.items()
            if k.startswith("stage_c_") and isinstance(v, dict)
        },
        dependencies=dependencies,
        archived_seconds=archived_seconds,
        recovery_seconds=perf_counter() - tick - archived_seconds,
        no_immutable_input_store_or_old_fit_copies=True,
        scope="Completed account/source replays and frozen sensitivities plus current bounded data intermediates; data composition/refits and C/D are not complete.",
    )
    output = Path(run["root"]) / "matched_economics_recovery.json"
    write_json_atomic(output, report)
    write_json_atomic(PROJECT / "docs/v2_matched_economics_recovery.json", report)
    run["stage_c_account_recovery"] = binding(output)
    write_json_atomic(pointer, run)
    print(json.dumps(report), flush=True)


if __name__ == "__main__":
    main()
